version: '3.4'
services:

    mongo.me.api:
        container_name: mongo.me
        image: mongo:latest
        ports:
            - 37017:27017

    mongo.me.authorization:
        container_name: mongo.me.authorization
        image: mongo:latest
        ports:
            - 47017:27017

    redis.me.authorization:
        container_name: redis.me.authorization
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis.me.authorization
        ports:
            - "7379:6379"

    prometheus.api.me:
        container_name: prometheus.api.me
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
